name: Volume and Price Checker

on:
  schedule:
    - cron: '*/15 * * * *'  # Se ejecuta cada 15 min para alertas y noticias
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-volume-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests yfinance pandas pytz

      - name: Run script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python volume_checker.py

      - name: Save state cache
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update market cache state"
          file_pattern: "*.json"
